---
data_dir: "/storage/efoglia/01_data/02_lbm/01_marlene_5deg"  # "/home/efoglia/Documents/02_data/05_cd_isae_beamforming" 
out_dir_root: "./out"
case_name: "lbm" #"CD-ISAE-5deg-40pr-rmp22-26-1.h5"
rmp_index: 12
compute_all: false
type: "lbm" # "lbm" or "beamforming"
# Physical parameters
p_ref: 2.0e-5
sound_speed: 343.0
microphone_distance: 1.45
micro_index: 0 # 29
# wavelet
wavelet: db24
# Welch 
welch:
  nperseg_factor: 3
  window: hann
# Signal conditioning parameters
conditioning:
  standardize: false
  detrend: true
  detrend_degree: 0
  bandpass_filter:
    apply: true
    lowcut: 100.0 # Check Anna Caiazzo's parameters
    highcut: 10000.0 # Check Anna Caiazzo's parameters
plots:
  frequency_range:
    min: 20
    max: 20000.0
  spectrum_range:
    min: -120
    max: 100
  spectrum_micro_range:
    min: -60
    max: 40
