---
data_dir: "/home/efoglia/Documents/02_data/05_cd_isae_beamforming"
out_dir_root: "./out"
out_dir: "./out/CD-ISAE-0deg-40pr-rmp22-26-90s-1"
case_name: "CD-ISAE-0deg-40pr-rmp22-26-90s-1.h5"
rmp_index: 0
compute_all: false
# Physical parameters
p_ref: 2.0e-5
sound_speed: 343.0
microphone_distance: 1.45
# Signal conditioning parameters
conditioning:
  standardize: false
  detrend: true
  detrend_degree: 0
  bandpass_filter:
    apply: true
    lowcut: 100.0 # Check Anna Caiazzo's parameters
    highcut: 10000.0 # Check Anna Caiazzo's parameters
