---
# data_dir:  "/home/efoglia/Documents/02_data/05_cd_isae_beamforming" 
data_dir: "/storage/efoglia/01_data/02_lbm/01_marlene_5deg"
out_dir_root: "./out"
# case_name: "CD-ISAE-5deg-40pr-rmp2-6-90s-1.h5"
case_name: "lbm"
rmp_index: 12
compute_all: false
type: "lbm" # "lbm" or "beamforming"
# Physical parameters
p_ref: 2.0e-5
sound_speed: 78.1517 # 343.0
microphone_distance: 0.1 # 1.45
micro_index: 0 # 29
# wavelet
wavelet: db24
# calibration
calibration:
  apply: false
  nperseg: 1024
  calibration_dir: "/storage/efoglia/01_data/03_expe/01_calibration_rmp/01-SPSPEAKER"
# Welch 
welch:
  nperseg_factor: 3
  window: hann
# Signal conditioning parameters
conditioning:
  standardize: false
  detrend: true
  detrend_degree: 0
  bandpass_filter:
    apply: true
    lowcut: 100.0 # Check Anna Caiazzo's parameters
    highcut: 20000.0 # Check Anna Caiazzo's parameters
plots:
  frequency_range:
    min: 200
    max: 50000.0
  spectrum_range:
    min: -60
    max: 80
  spectrum_micro_range:
    min: -60
    max: 40
